default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= ENV['DB_PASSWORD'] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: home_repair_services

# test:
#   <<: *default
#   database: backend_test
#
# production:
#   <<: *default
#   database: backend_production
#   username: backend
#   password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
